services:
  app:
    container_name: app_jurassic
    image: node:20-alpine
    working_dir: /app
    command: sh -c "corepack enable && pnpm install && pnpm exec next dev -H 0.0.0.0 -p 3000"
    environment:
      - DATABASE_URL=postgresql://jurassic:jurassic@db:5432/jurassic
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    container_name: db_jurassic
    image: postgres:15
    environment:
      - POSTGRES_USER=jurassic
      - POSTGRES_PASSWORD=jurassic
      - POSTGRES_DB=jurassic
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
