import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

export const metadata: Metadata = {
	title: "Jurassic park 2.0",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html
			lang='fr'
			className='light'
		>
			<body className='antialiased'>
				{" "}
				{/* Ajout de antialiased pour une typo plus propre */}
				<SidebarProvider defaultOpen={true}>
					<div className='flex min-h-screen w-full'>
						<AppSidebar />

						{/* CORRECTION ICI : Remplacer absolute par fixed */}
						<div className='fixed top-4 left-4 z-100'>
							<SidebarTrigger className='bg-slate-900/80 backdrop-blur-md border border-white/20 text-white hover:bg-white/20 rounded-md p-2 shadow-xl' />
						</div>

						<main className='flex-1 overflow-y-auto'>{children}</main>
					</div>
				</SidebarProvider>
			</body>
		</html>
	);
}
